version: '3'
services:
  nextjs-notion-blog:
    image: jhcode33/nextjs-server-image:${TAG}
    container_name: nextjs-notion-blog
    ports:
      - "3000:3000"
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"