version: "3.3"

networks:
  nextjs-notion-blog:
    external: true

services:
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    networks:
      - nextjs-notion-blog
    command: >
      certonly
      --webroot
      -w /var/www/certbot
      --agree-tos
      --email jhcode33@gmail.com
      --no-eff-email
      -d www.jhcode33.com
    volumes:
      - ${NGINX_ROOT}/certbot/conf:/etc/letsencrypt:rw     #인증서 경로
      - ${NGINX_ROOT}/certbot/logs:/var/log/letsencrypt:rw
      - ${NGINX_ROOT}/certbot/data:/var/www/certbot:rw     #인증서 웹루트 경로