version: '3.8'
services:
  nextjs-notion-blog:
    container_name: nextjs-notion-blog
    image: jhcode33/nextjs-notion-blog:${TAG}
    ports:
      - "3000:3000"
    networks:
      - nextjs-notion-blog

networks:
  nextjs-notion-blog:
    external: true