version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:7.4.1
    environment:
      - REDIS_PASSWORD='1234'
      - REDIS_USER='jhcode33'
    ports:
      - "6379:6379"
    restart: always

  nextjs-notion-blog:
    container_name: nextjs-notion-blog
    image: jhcode33/nextjs-notion-blog:1.0.0
    ports:
      - "3000:3000"
    depends_on:
      - redis
